{
    'name': 'My Flight',
    'version': '18.0.0.1',
    'summary': 'Flight and Hotel Booking',
    'sequence': 10,
    'description': """ """,
    'depends': ['base', 'contacts'],
    'data': [
        'security/ir.model.access.csv',
        'data/ir_sequence.xml',
        'data/action.xml',
        'demo/demo.xml',
        'views/bookng_conf.xml',
        'views/flight_search.xml',
        'views/iata_code.xml',
        'views/flight_api_log.xml',
        'views/flight_air_ticket.xml',

        'views/hotel_api_log.xml',
        'views/hotel_booking.xml',
        'views/hotel_room_search.xml',
        'views/hotel_booking_detail.xml',
        'views/res_country_city.xml',
        'wizard/flight_pricing_wizard.xml',
        'wizard/hotel_room_wizard.xml',
        'wizard/hotel_cancel_wizard.xml',
        # 'wizard/flight_travel_class_wizard.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
